# Generated by Django 6.0 on 2025-12-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_it',
            new_name='student_id',
        ),
    ]
