# Generated by Django 6.0 on 2025-12-22 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogg',
            old_name='blogge_title',
            new_name='blogger_title',
        ),
    ]
